version: "3.5"

services:
    nginx:
      build: ./nginx
      ports:
        - "8080:80"
      volumes:
        - ./nginx/logs:/var/log/nginx

    node:
      build: ./app
      tty: true
      volumes:
        - ./app:/var/www/app
